# Generated by Django 2.2b1 on 2019-06-14 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20190604_0505'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.CharField(default='', max_length=100)),
                ('installment', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('basicperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.BasicPerson')),
                ('department', models.TextField(default='', max_length=300)),
                ('salary', models.CharField(default='', max_length=1000)),
                ('designation', models.TextField(default='', max_length=200)),
                ('timings_of_duty', models.CharField(default='', max_length=200)),
                ('qualification', models.CharField(default='', max_length=300)),
            ],
            bases=('home.basicperson',),
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
