# Generated by Django 2.2b1 on 2019-06-15 09:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_employee_salary'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('salary', django.db.models.manager.Manager()),
            ],
        ),
    ]
