# Generated by Django 2.2b1 on 2019-06-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190615_1431'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='et',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='st',
            field=models.CharField(default='', max_length=10),
        ),
    ]
