# Generated by Django 2.2b1 on 2019-06-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190615_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tt',
            field=models.CharField(default='', max_length=10),
        ),
    ]
