# Generated by Django 2.2b1 on 2019-06-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_employee_tt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='et',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='st',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='tt',
            new_name='total_hours',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='timings_of_duty',
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualification',
            field=models.CharField(default='', max_length=200),
        ),
    ]
