# Generated by Django 2.2b1 on 2019-06-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190615_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='end_time',
            new_name='et',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='start_time',
            new_name='st',
        ),
    ]
