# Generated by Django 2.2b1 on 2019-06-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190615_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
