# Generated by Django 2.2b1 on 2019-06-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customers_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='username',
        ),
        migrations.AddField(
            model_name='customers',
            name='c_email',
            field=models.EmailField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='customers',
            name='c_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
    ]
