# Generated by Django 2.2b1 on 2019-06-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190619_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='c_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='c_name',
            new_name='name',
        ),
    ]
