# Generated by Django 2.2.1 on 2019-06-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_descr', models.CharField(default='', max_length=200)),
                ('p_price', models.IntegerField(default=0)),
                ('p_quantity', models.IntegerField(default=0)),
                ('model_no', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
