# Generated by Django 2.2.1 on 2019-06-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20190603_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='samsung',
            name='product_image',
            field=models.ImageField(default=None, upload_to='Samsung/images'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='model_no',
            field=models.CharField(default='', max_length=50),
        ),
    ]
