# Generated by Django 2.2.1 on 2019-06-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_auto_20190603_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='samsung',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
