# Generated by Django 2.2.1 on 2019-06-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_samsung_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samsung',
            name='product_name',
        ),
    ]
