# Generated by Django 2.2.1 on 2019-06-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_remove_samsung_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samsung',
            old_name='model_no',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='samsung',
            name='product_image',
        ),
    ]
