# Generated by Django 2.2.1 on 2019-06-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0007_auto_20190603_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='samsung',
            name='product_image',
            field=models.ImageField(default=None, upload_to='Samsung/images'),
        ),
    ]
