# Generated by Django 2.2.1 on 2019-06-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_auto_20190604_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_model', models.CharField(default='', max_length=50)),
                ('product_descr', models.CharField(default='', max_length=200)),
                ('product_price', models.IntegerField(default=0)),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_brand', models.CharField(default='', max_length=40)),
                ('product_image', models.ImageField(default=None, upload_to='Mobile/Accessories/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='mobile',
            name='product_image',
            field=models.ImageField(default=None, upload_to='Mobile/Mobile/images'),
        ),
    ]
