# Generated by Django 2.2.1 on 2019-06-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0012_auto_20190607_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='product_model',
            field=models.CharField(default='', max_length=500),
        ),
    ]
