# Generated by Django 2.2.1 on 2019-06-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0013_auto_20190609_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='product_features',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='product_descr',
            field=models.CharField(default='', max_length=200),
        ),
    ]
