# Generated by Django 2.2.1 on 2019-06-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0014_auto_20190610_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='product_features',
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_descr',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='product_descr',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
