# Generated by Django 2.2b1 on 2019-07-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0015_auto_20190610_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='product_descr',
            field=models.TextField(default='N.A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='product_image',
            field=models.ImageField(default='N.A', upload_to='Mobile/images'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='product_model',
            field=models.CharField(default='N.A', max_length=500),
        ),
    ]
