# Generated by Django 2.2.2 on 2019-07-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0016_auto_20190706_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessories',
        ),
    ]
