# Generated by Django 2.2.1 on 2019-06-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('Help', models.IntegerField(default='')),
                ('address', models.CharField(max_length=100)),
                ('NIC_No', models.IntegerField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
