# Generated by Django 2.2.1 on 2019-06-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicperson',
            name='email',
        ),
        migrations.AlterField(
            model_name='basicperson',
            name='NIC_No',
            field=models.IntegerField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='basicperson',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
