# Generated by Django 2.2.1 on 2019-06-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190603_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicperson',
            name='NIC_No',
            field=models.IntegerField(default=0),
        ),
    ]
