# Generated by Django 2.2.2 on 2019-07-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190604_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicperson',
            name='Help',
        ),
        migrations.AddField(
            model_name='basicperson',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
